-- REVIEW PROPOSAL ONLY. Not applied. Requires per-app catalog/ACL, restore,
-- secure credential handoff and coordinator cutover approval described in database-runtime-access.md.
-- Adoption must have completed before this script. This script creates NOLOGIN roles;
-- enabling approved migration/runtime logins and private credential injection is an owner-only step.
-- This removes PUBLIC CONNECT/TEMP only on the selected app database after consumer review.
-- Rights inherited in other databases remain a separate reviewed gate.
\set ON_ERROR_STOP on
BEGIN;
DO $$ BEGIN IF current_database() <> 'macro_tracker' THEN RAISE EXCEPTION 'Wrong database'; END IF; END $$;
DO $$ BEGIN IF to_regclass('public.app_schema_versions') IS NULL THEN RAISE EXCEPTION 'Adopt schema first'; END IF; END $$;
CREATE ROLE macrovana_owner NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE macrovana_migrator NOLOGIN NOINHERIT NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
CREATE ROLE macrovana_runtime NOLOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS;
GRANT macrovana_owner TO macrovana_migrator WITH INHERIT FALSE;
-- Add explicit CONNECT grants for any additional catalog-verified legitimate consumers before approval.
REVOKE ALL ON DATABASE macro_tracker FROM PUBLIC;
GRANT CONNECT ON DATABASE macro_tracker TO macrovana_migrator, macrovana_runtime;
ALTER SCHEMA public OWNER TO macrovana_owner;
-- Before approval, enumerate and preserve any additional legitimate schema users.
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
GRANT USAGE ON SCHEMA public TO macrovana_runtime;
ALTER TABLE public.analysis_reports OWNER TO macrovana_owner;
REVOKE ALL ON public.analysis_reports FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.analysis_reports TO macrovana_runtime;
ALTER TABLE public.api_tokens OWNER TO macrovana_owner;
REVOKE ALL ON public.api_tokens FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.api_tokens TO macrovana_runtime;
ALTER TABLE public.audit_log OWNER TO macrovana_owner;
REVOKE ALL ON public.audit_log FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.audit_log TO macrovana_runtime;
ALTER TABLE public.billing_events OWNER TO macrovana_owner;
REVOKE ALL ON public.billing_events FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.billing_events TO macrovana_runtime;
ALTER TABLE public.client_diagnostics OWNER TO macrovana_owner;
REVOKE ALL ON public.client_diagnostics FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.client_diagnostics TO macrovana_runtime;
ALTER TABLE public.client_mutations OWNER TO macrovana_owner;
REVOKE ALL ON public.client_mutations FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.client_mutations TO macrovana_runtime;
ALTER TABLE public.coach_dismissals OWNER TO macrovana_owner;
REVOKE ALL ON public.coach_dismissals FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.coach_dismissals TO macrovana_runtime;
ALTER TABLE public.daily_usage_counts OWNER TO macrovana_owner;
REVOKE ALL ON public.daily_usage_counts FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.daily_usage_counts TO macrovana_runtime;
ALTER TABLE public.entries OWNER TO macrovana_owner;
REVOKE ALL ON public.entries FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.entries TO macrovana_runtime;
ALTER TABLE public.food_corrections OWNER TO macrovana_owner;
REVOKE ALL ON public.food_corrections FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.food_corrections TO macrovana_runtime;
ALTER TABLE public.health_transport_coverage OWNER TO macrovana_owner;
REVOKE ALL ON public.health_transport_coverage FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.health_transport_coverage TO macrovana_runtime;
ALTER TABLE public.integration_data_permissions OWNER TO macrovana_owner;
REVOKE ALL ON public.integration_data_permissions FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.integration_data_permissions TO macrovana_runtime;
ALTER TABLE public.macro_targets OWNER TO macrovana_owner;
REVOKE ALL ON public.macro_targets FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.macro_targets TO macrovana_runtime;
ALTER TABLE public.nutrition_day_completeness OWNER TO macrovana_owner;
REVOKE ALL ON public.nutrition_day_completeness FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.nutrition_day_completeness TO macrovana_runtime;
ALTER TABLE public.oura_connections OWNER TO macrovana_owner;
REVOKE ALL ON public.oura_connections FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.oura_connections TO macrovana_runtime;
ALTER TABLE public.oura_documents OWNER TO macrovana_owner;
REVOKE ALL ON public.oura_documents FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.oura_documents TO macrovana_runtime;
ALTER TABLE public.oura_oauth_states OWNER TO macrovana_owner;
REVOKE ALL ON public.oura_oauth_states FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.oura_oauth_states TO macrovana_runtime;
ALTER TABLE public.oura_webhook_subscriptions OWNER TO macrovana_owner;
REVOKE ALL ON public.oura_webhook_subscriptions FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.oura_webhook_subscriptions TO macrovana_runtime;
ALTER TABLE public.progress_checkins OWNER TO macrovana_owner;
REVOKE ALL ON public.progress_checkins FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.progress_checkins TO macrovana_runtime;
ALTER TABLE public.progress_photos OWNER TO macrovana_owner;
REVOKE ALL ON public.progress_photos FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.progress_photos TO macrovana_runtime;
ALTER TABLE public.rate_limit_counters OWNER TO macrovana_owner;
REVOKE ALL ON public.rate_limit_counters FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.rate_limit_counters TO macrovana_runtime;
ALTER TABLE public.saved_items OWNER TO macrovana_owner;
REVOKE ALL ON public.saved_items FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.saved_items TO macrovana_runtime;
ALTER TABLE public.sexual_activity_entries OWNER TO macrovana_owner;
REVOKE ALL ON public.sexual_activity_entries FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sexual_activity_entries TO macrovana_runtime;
ALTER TABLE public.sleep_entries OWNER TO macrovana_owner;
REVOKE ALL ON public.sleep_entries FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.sleep_entries TO macrovana_runtime;
ALTER TABLE public.subscriptions OWNER TO macrovana_owner;
REVOKE ALL ON public.subscriptions FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.subscriptions TO macrovana_runtime;
ALTER TABLE public.user_identities OWNER TO macrovana_owner;
REVOKE ALL ON public.user_identities FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_identities TO macrovana_runtime;
ALTER TABLE public.users OWNER TO macrovana_owner;
REVOKE ALL ON public.users FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.users TO macrovana_runtime;
ALTER TABLE public.waist_entries OWNER TO macrovana_owner;
REVOKE ALL ON public.waist_entries FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.waist_entries TO macrovana_runtime;
ALTER TABLE public.web_sessions OWNER TO macrovana_owner;
REVOKE ALL ON public.web_sessions FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.web_sessions TO macrovana_runtime;
ALTER TABLE public.webhook_events OWNER TO macrovana_owner;
REVOKE ALL ON public.webhook_events FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.webhook_events TO macrovana_runtime;
ALTER TABLE public.weight_entries OWNER TO macrovana_owner;
REVOKE ALL ON public.weight_entries FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.weight_entries TO macrovana_runtime;
ALTER TABLE public.weight_targets OWNER TO macrovana_owner;
REVOKE ALL ON public.weight_targets FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.weight_targets TO macrovana_runtime;
ALTER TABLE public.workout_entries OWNER TO macrovana_owner;
REVOKE ALL ON public.workout_entries FROM PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.workout_entries TO macrovana_runtime;
ALTER TABLE public.app_schema_versions OWNER TO macrovana_owner;
REVOKE ALL ON public.app_schema_versions FROM PUBLIC;
GRANT SELECT ON public.app_schema_versions TO macrovana_runtime;
ALTER TABLE public.schema_migrations OWNER TO macrovana_owner;
REVOKE ALL ON public.schema_migrations FROM PUBLIC;
GRANT SELECT ON public.schema_migrations TO macrovana_runtime;
ALTER SEQUENCE public.analysis_reports_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.analysis_reports_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.analysis_reports_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.api_tokens_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.api_tokens_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.api_tokens_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.audit_log_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.audit_log_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.audit_log_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.billing_events_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.billing_events_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.billing_events_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.client_diagnostics_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.client_diagnostics_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.client_diagnostics_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.entries_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.entries_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.entries_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.saved_items_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.saved_items_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.saved_items_id_seq TO macrovana_runtime;
DO $$ BEGIN
  IF (to_regclass('public.sexual_activity_entries_id_seq') IS NOT NULL)::int + (to_regclass('public.ejaculation_entries_id_seq') IS NOT NULL)::int <> 1 THEN
    RAISE EXCEPTION 'Expected exactly one reviewed sexual-activity sequence';
  END IF;
  IF to_regclass('public.sexual_activity_entries_id_seq') IS NOT NULL THEN
    ALTER SEQUENCE public.sexual_activity_entries_id_seq OWNER TO macrovana_owner;
    REVOKE ALL ON SEQUENCE public.sexual_activity_entries_id_seq FROM PUBLIC;
    GRANT USAGE ON SEQUENCE public.sexual_activity_entries_id_seq TO macrovana_runtime;
  ELSE
    ALTER SEQUENCE public.ejaculation_entries_id_seq OWNER TO macrovana_owner;
    REVOKE ALL ON SEQUENCE public.ejaculation_entries_id_seq FROM PUBLIC;
    GRANT USAGE ON SEQUENCE public.ejaculation_entries_id_seq TO macrovana_runtime;
  END IF;
END $$;
ALTER SEQUENCE public.sleep_entries_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.sleep_entries_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.sleep_entries_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.subscriptions_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.subscriptions_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.subscriptions_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.waist_entries_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.waist_entries_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.waist_entries_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.webhook_events_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.webhook_events_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.webhook_events_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.weight_entries_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.weight_entries_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.weight_entries_id_seq TO macrovana_runtime;
ALTER SEQUENCE public.workout_entries_id_seq OWNER TO macrovana_owner;
REVOKE ALL ON SEQUENCE public.workout_entries_id_seq FROM PUBLIC;
GRANT USAGE ON SEQUENCE public.workout_entries_id_seq TO macrovana_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE macrovana_owner REVOKE EXECUTE ON FUNCTIONS FROM PUBLIC;
-- New tables/sequences get no default runtime grants; each migration grants its reviewed objects.
-- Database/extension ownership and shared admin credentials are intentionally untouched.
COMMIT;
